### ISSUE TITLE
Cannot find Module hltv-api

### ISSUE THREAD

**Issue by madsj1** [dajk/hltv-api#11]
Hello again, after updating to ur latest update it seems nothing except package.json and readme file is getting installed with npm install hltv-api.
Did something break on last update?

**Comment by dajk** [comment]
Hi @madsj1 , thanks for reporting this bug.
Seems that yarn on travis are causing this issue. I'll check that when I find the time.

**Comment by madsj1** [comment]
Thank you!

**Comment by dajk** [comment]
This is fixed. Feel free to reopen if you still have issues.
