### ISSUE TITLE
Map (maps) JSON shortcuts and names

### ISSUE THREAD

**Issue by VaolEr** [dajk/hltv-api#53]
Hello!
Firs of all thank You for API. As for start using APIs it is perfect: easy to understood and there is internet service which provides it!

And now to the point. There will be 3 questions.

1. I found, that there is difference between JSON object structures in response for `/matches` and `/results:` for /matches we have field `maps` and for  /results we have filed `map`. Maybe it is will be more correct to change this field to single name, because for both requests we can get `bo3` or `bo5` in response.
2. In readme as example we have response filed `"map": "Inferno"`, for request `/matches`, but in real we have `"map": "inf"`. So it is little incorrect API documentation.
3. It is will be cool if you will add the list of shortcuts and map names to documentation. I found next dependencies:
    MAP("shortcut", "map name")
-------------------------------------------------
    ANCIENT ("anc", "Ancient"),         
    BO5 ("bo5", "Best of 5"),           
    BO3 ("bo3", "Best of 3"),            
    CACHE ("???","Cache"),
    SEASON ("???","Season"),
    DUST2("d2","Dust2"),                
    MIRAGE("mrg","Mirage"),             
    INFERNO("inf","Inferno"),          
    NUKE("nuke","Nuke"),               
    TRAIN("trn","Train"),               
    COBBLESTONE("???","Cobblestone"),
    OVERPASS("ovp","Overpass"),       
    TUSCAN("tsc","Tuscan"),
    VERTIGO("vtg","Vertigo"),          
    CONFLICT("-", "Conflict situation") 
-------------------------------------------------
Thank you!

**Comment by dajk** [comment]
Hi @VaolEr 

In my opinion, anyone who uses the api can do the mapping on their own. Think of that as short names as an Ids of the maps.

I hope that makes sense
