### ISSUE TITLE
export types used by methods

### ISSUE THREAD

**Issue by AuroraDysis** [dajk/hltv-api#71]
e.g. IEvent, ITeam, IMatch

**Comment by dajk** [comment]
Can you explain why is that needed?

**Comment by AuroraDysis** [comment]
Thanks for your reply. This will be very useful when one wants to define typescript functions.

**Comment by dajk** [comment]
Usually you can inherit types from the origin function, for instance `type Matches = Awaited<ReturnType<typeof HLTV.getMatches>>`

**Comment by AuroraDysis** [comment]
This is exactly what I use now and why I opened this issue.
I need to manually export all the types used which is inconvenient.
If you are willing to improve this point, I can open a pull request.
