### ISSUE TITLE
Not working on Local

### ISSUE THREAD

**Issue by User013103123** [dajk/hltv-api#84]
Hi! 
I try to start this lib, but its not woking....

Here whats my Express server send -- 
$\HLTV\node_modules\hltv-api\dist\matches.js:74
            throw new Error(error);
                  ^

Error: Error: There are no matches available, something went wrong. Please contact the library maintainer on https://github.com/dajk/hltv-api
    at Object.<anonymous> $HLTV\node_modules\hltv-api\dist\matches.js:74:19)
    at Generator.next (<anonymous>)
    at fulfilled ($\HLTV\node_modules\hltv-api\dist\matches.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.3.0

Help me out, pls

**Comment by dajk** [comment]
You can try again, seems the fix should be in place already. Feel free to re-open if something is still not working.
